---
- name: Pull postgresql container
  raw: docker pull orchardup/postgresql

- name: Create postgresql.service file
  template: src=postgresql.service.j2 dest=/etc/systemd/system/postgresql.service owner=root

- name: Start postgresql service
  service: name=postgresql state=started enabled=yes
  notify:
    - Start cluster services
