---
- name: pgdata exist?
  raw: "docker ps -a | grep pgdata"
  ignore_errors: True
  register: pgdata_exists

- name: launch data container
  raw:  docker run -d -v /var/lib/postgresql --name pgdata joemocha/data echo 'Postgresql Data Container'
  when: pgdata_exists|failed

- name: Postgresql running?
  raw: "docker ps -a | grep postgresql"
  ignore_errors: True
  register: postgresql_is_running

- name: Pull Postgresql image
  raw: docker pull orchardup/postgresql
  when: postgresql_is_running|failed

- name: Start Postgresql container
  raw: docker run -d --name=db --volumes-from pgdata -e POSTGRESQL_USER={{ postgresql.user }} -e POSTGRESQL_DB={{ postgresql.db }} -e POSTGRESQL_PASS={{ postgresql.password }} -p 5432:5432 orchardup/postgresql
  when: postgresql_is_running|failed
