---
- name: launch data container
  docker:
    image: joemocha/data
    name: pgdata
    state: present
    volumes: /var/lib/postgresql
    command: echo "Postgresql Data Container"

- name: Pull postgresql container
  raw: docker pull orchardup/postgresql

- name: Create postgresql.service file
  template: src=postgresql.service.j2 dest={{ service_path }}/postgresql@.service owner=root

- name: Create postgresql discovery unit
  template: src=postgresql-discovery.service.j2 dest={{ service_path }}/postgresql-discovery@.service owner=root

- name: Submit postgresql services
  raw: fleetctl submit {{ service_path }}/postgresql@.service {{ service_path }}/postgresql-discovery@.service
