---
- name: Pull redis container
  raw: docker pull redis
- name: Create redis.service file
  template: src=redis.service.j2 dest=/etc/systemd/system/redis@.service owner=root
- name: Redis service state
  service: name=redis state=started enabled=yes
