---
- name: Pull redis container
  raw: docker pull redis

- name: Create redis service
  template: src=redis.service.j2 dest={{ service_path }}/redis@.service owner=root

- name: Create redis discovery service
  template: src=redis-discovery.service.j2 dest={{ service_path }}/redis-discovery@.service owner=root

- name: Submit redis services
  raw: fleetctl submit {{ service_path }}/redis@.service {{ service_path }}/redis-discovery@.service
