---
- name: Pull redis container
  raw: docker pull redis

- name: Create redis service
  template: src=redis.service.j2 dest=/etc/systemd/system/redis@.service owner=root
  notify:
    - Submit cluster services
