---
- name: Pull Redis image
  raw: docker pull redis

- name: Redis running?
  raw: "docker ps | grep redis"
  ignore_errors: True
  register: redis_is_running

- name: Start Redis
  raw: docker run -d --name redis -p 6379:6379 redis
  when: redis_is_running|failed
