---
- name: Load Balancer running?
  raw: "docker ps | grep load_balancer"
  ignore_errors: True
  register: nginx_is_running

- name: Build nginx image
  raw: cd {{ nginx.directory}} && docker build -t joemocha/load_balancer .
  when: nginx_is_running|failed

- name: Start Load Balancer
  raw: docker run -d --name lb -p 80:80 -e ETCD=172.12.8.101:4001 -e HOST_IP={{ load_balancer }} joemocha/load_balancer
  when: nginx_is_running|failed
