---
- name: Pull nginx container
  raw: cd share/nginx && docker build -t joemocha/load_balancer .

- name: Create nginx.service file
  template: src=nginx.service.j2 dest=/etc/systemd/system/nginx.service owner=root
  notify:
    - Submit cluster services

