---
- name: Pull haproxy container
  raw: docker pull tutum/haproxy

- name: Create haproxy service file
  template: src=haproxy.service.j2 dest=/etc/systemd/system/haproxy@.service owner=root
  notify:
    - Submit cluster services
