---
- name: Pull haproxy container
  raw: docker pull tutum/haproxy

- name: Create haproxy service file
  template: src=haproxy.service.j2 dest={{ service_path }}/haproxy@.service owner=root

- name: Submit haproxy services
  raw: fleetctl submit {{ service_path }}/haproxy@.service
