- name: Reset server services
  hosts: coreos
  sudo: true
  roles:
    - common
  tasks:
    - name: Destroy service units
      raw: fleetctl destroy {{ services | join(' ') }}
    - name: Destroy service template units
      raw: fleetctl destroy {{ service_templates | join(' ') }}
