- name: Reset server services
  hosts: leader
  sudo: true
  roles:
    - common
  tasks:
    - name: Destroy service templates
      raw: fleetctl destroy {{ services | join(' ') }} {{ service_templates | join(' ') }}
