- name: Services
  hosts: leader
  sudo: true
  tasks:
    - name: Start Redis
      raw: fleetctl start redis@6379 redis-discovery@6379

    - name: Start Memcached
      raw: fleetctl start memcached@11211 memcached-discovery@11211

    - name: Start Postgresql
      raw: fleetctl start postgresql@5432 postgresql-discovery@5432

    - name: Start API
      raw: fleetctl start api@80 api-discovery@80

    - name: Start Nginx
      raw: fleetctl start nginx nginx-discovery
