---
- name: Build api container
  docker_image: path="/home/core/share/api" name="joemocha/api" state=present

- name: Create api discovery service
  template: src=api-discovery.service.j2 dest=/etc/systemd/system/api-discovery@.service owner=root
  notify:
    - Submit cluster services

- name: Create api.service file
  template: src=api.service.j2 dest=/etc/systemd/system/api@.service owner=root
  notify:
    - Submit cluster services
