---
- name: Build api container
  docker_image:
    path="/home/core/share/api"
    name="joemocha/api"
    state=present

- name: Create api discovery service
  template: src=api-discovery.service.j2 dest={{ service_path }}/api-discovery@.service owner=root

- name: Create api.service file
  template: src=api.service.j2 dest={{ service_path }}/api@.service owner=root

- name: Submit api services
  raw: fleetctl submit {{ service_path }}/api@.service {{ service_path }}/api-discovery@.service
