---
- name: Build app container
  docker_image: path="/home/core/share/app" name="joemocha/app" state=present

- name: Create app service file
  template: src=app.service.j2 dest={{ service_path }}/app@.service owner=root

# - name: Submit app services
  # raw: fleetctl submit {{ service_path }}/app@.service {{ service_path }}/app-discovery@.service
