---
- name: build data container
  docker_image: path="/home/core/share/data" name="joemocha/data" state=present
- name: launch data container
  docker:
    image: joemocha/data
    name: pgdata
    state: running
    volumes: /var/lib/postgresql
    command: echo "Postgresql Data Container"
