---
service_path: /tmp/services
service_templates:
  - redis@
  - redis-discovery@
  - memcached@
  - memcached-discovery@
  - postgresql@
  - postgresql-discovery@
  - api@
  - api-discovery@
services:
  - redis@6379
  - redis-discovery@6379
  - memcached@11211
  - memcached-discovery@11211
  - postgresql@5432
  - postgresql-discovery@5432
  - api@80
  - api-discovery@80
  - nginx
  - nginx-discovery
