---
env: development
service_path: /tmp/services
service_templates:
  - app@
  - app-discovery@
  - api@
  - api-discovery@
services:
  - api@80
  - api-discovery@80
  - app@8080
  - app-discovery@8080
memcached:
  password: "{{ lookup('password', '/tmp/memcached chars=ascii_letters,digits,hexdigits length=24') }}"
postgresql:
  db: atp
  user: atp
  password: "{{ lookup('password', '/tmp/postgresql chars=ascii_letters,digits,hexdigits length=24') }}"
nginx:
  directory: /Users/sam/workspace/atp/nginx
