---
- name: Pull memcached container
  raw: docker pull tutum/memcached

- name: is memcached running
  raw: "docker ps | grep tutum/memcached"
  ignore_errors: True
  register: memcached_is_running

- name: start memcached container
  raw: "docker run -d -e MEMCACHED_PASS={{ memcached.password }} -p 11211:11211 --name cache tutum/memcached"
  when: memcached_is_running|failed
