---
- name: Pull memcached container
  raw: docker pull tutum/memcached

- name: Create memcached.service file
  template: src=memcached.service.j2 dest=/etc/systemd/system/memcached@.service owner=root
  notify: 
    - Submit cluster services
